### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by 9tail123** [c0cc/code_obfuscate#1]
混淆python脚本时会报错找不到pyc文件，比如gb.py    PyFileObfuscate类好像只是找的gb.pyc，没有去__pycache__目录下找，而且我的pyc文件是gb.cpython-37.pyc这样子的

**Comment by MiniSafe** [comment]
抱歉咯，这个现在还是写得玩的，目前只支持了python2.7，PyFileObfuscate这个东西在打开文件的时候是会编译一下py文件，并且到同目录下寻找pyc文件，如果有疑问可以手工去生成pyc文件，提取pyc文件中的code对象，使用CodeObfuscate对字节码进行混淆，把修改完的内容写带上魔术字加时间戳，加上序列化后的code对象拼成pyc文件重新写进去就好，但是py3好像从3.6开始，pyc文件结构就不太一样了

**Comment by MiniSafe** [comment]
具体可以参考文件code_obfuscate/obfuscate.py在第259行的PycFileObfuscate的构造方法，这里面记录了如何读取时间戳和魔术字，以及下面的write方法写了如何写入魔术字和时间戳

**Comment by 9tail123** [comment]
好的，谢谢大佬
